# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jerry\Documents\RunquanGIt\Python\GoogleTranslator\pythonTranslator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLabel
from PyQt5.QtGui import QIcon, QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 423)
        MainWindow.setToolTipDuration(0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QLineEdit{border: 0.5px solid red; border-radius:50%;}")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhExclusiveInputMask)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lookUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.lookUpButton.setGeometry(QtCore.QRect(587, 17, 82, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.lookUpButton.setFont(font)
        self.lookUpButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lookUpButton.setMouseTracking(False)
        self.lookUpButton.setStyleSheet("background-color: #80ff80;\n"
"")
        self.lookUpButton.setObjectName("lookUpButton")
        self.wordTranslate = QtWidgets.QScrollArea(self.centralwidget)
        self.wordTranslate.setGeometry(QtCore.QRect(20, 68, 650, 301))
        self.wordTranslate.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.wordTranslate.setWidgetResizable(True)
        self.wordTranslate.setObjectName("wordTranslate")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 648, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.wordTranslate.setWidget(self.scrollAreaWidgetContents)
        self.inputWord = QtWidgets.QLineEdit(self.centralwidget)
        self.inputWord.setGeometry(QtCore.QRect(20, 17, 551, 31))
        self.inputWord.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhUppercaseOnly|QtCore.Qt.ImhUrlCharactersOnly)
        self.inputWord.setText("")
        self.inputWord.setObjectName("inputWord")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setObjectName("menuFile")
        self.menuTranslate = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.menuTranslate.setFont(font)
        self.menuTranslate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuTranslate.setObjectName("menuTranslate")
        self.menuTranslate_Options = QtWidgets.QMenu(self.menuTranslate)
        self.menuTranslate_Options.setObjectName("menuTranslate_Options")
        self.menuPrograme_Language = QtWidgets.QMenu(self.menuTranslate)
        self.menuPrograme_Language.setObjectName("menuPrograme_Language")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAbout_Project = QtWidgets.QAction(MainWindow)
        self.actionAbout_Project.setObjectName("actionAbout_Project")
        self.actionAbout_Programmer = QtWidgets.QAction(MainWindow)
        self.actionAbout_Programmer.setObjectName("actionAbout_Programmer")
        self.actionConnect_Me = QtWidgets.QAction(MainWindow)
        self.actionConnect_Me.setObjectName("actionConnect_Me")
        self.actionSearch_Word = QtWidgets.QAction(MainWindow)
        self.actionSearch_Word.setObjectName("actionSearch_Word")
        self.actionTranslate_Document = QtWidgets.QAction(MainWindow)
        self.actionTranslate_Document.setObjectName("actionTranslate_Document")
        self.actionDetect_Language = QtWidgets.QAction(MainWindow)
        self.actionDetect_Language.setObjectName("actionDetect_Language")
        self.actionPrograme_Language = QtWidgets.QAction(MainWindow)
        self.actionPrograme_Language.setObjectName("actionPrograme_Language")
        self.actionPrograme_Language_2 = QtWidgets.QAction(MainWindow)
        self.actionPrograme_Language_2.setObjectName("actionPrograme_Language_2")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionChinese = QtWidgets.QAction(MainWindow)
        self.actionChinese.setObjectName("actionChinese")
        self.actionJapanese = QtWidgets.QAction(MainWindow)
        self.actionJapanese.setObjectName("actionJapanese")
        self.actionOther_s = QtWidgets.QAction(MainWindow)
        self.actionOther_s.setObjectName("actionOther_s")
        self.actionEnglish_2 = QtWidgets.QAction(MainWindow)
        self.actionEnglish_2.setObjectName("actionEnglish_2")
        self.actionChinese_2 = QtWidgets.QAction(MainWindow)
        self.actionChinese_2.setObjectName("actionChinese_2")
        self.actionJapanese_2 = QtWidgets.QAction(MainWindow)
        self.actionJapanese_2.setObjectName("actionJapanese_2")
        self.actionOther_s_2 = QtWidgets.QAction(MainWindow)
        self.actionOther_s_2.setObjectName("actionOther_s_2")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionQuit)
        self.menuTranslate_Options.addAction(self.actionEnglish)
        self.menuTranslate_Options.addAction(self.actionChinese)
        self.menuTranslate_Options.addAction(self.actionJapanese)
        self.menuTranslate_Options.addAction(self.actionOther_s)
        self.menuPrograme_Language.addAction(self.actionEnglish_2)
        self.menuPrograme_Language.addAction(self.actionChinese_2)
        self.menuPrograme_Language.addAction(self.actionJapanese_2)
        self.menuPrograme_Language.addAction(self.actionOther_s_2)
        self.menuTranslate.addAction(self.actionSearch_Word)
        self.menuTranslate.addAction(self.actionTranslate_Document)
        self.menuTranslate.addAction(self.actionDetect_Language)
        self.menuTranslate.addAction(self.menuTranslate_Options.menuAction())
        self.menuTranslate.addAction(self.menuPrograme_Language.menuAction())
        self.menuAbout.addAction(self.actionAbout_Project)
        self.menuAbout.addAction(self.actionAbout_Programmer)
        self.menuAbout.addAction(self.actionConnect_Me)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTranslate.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        label = QLabel(self)
        pixmap = QPixmap('bg.jpeg')
        label.setPixmap(pixmap)
        self.resize(pixmap.width(),pixmap.height())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Tranlator"))
        self.lookUpButton.setText(_translate("MainWindow", "Look Up"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTranslate.setTitle(_translate("MainWindow", "Translate"))
        self.menuTranslate_Options.setTitle(_translate("MainWindow", "Translate Options"))
        self.menuPrograme_Language.setTitle(_translate("MainWindow", "Programe Language"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionAbout_Project.setText(_translate("MainWindow", "About Project"))
        self.actionAbout_Programmer.setText(_translate("MainWindow", "About Programmer"))
        self.actionConnect_Me.setText(_translate("MainWindow", "Connect Me"))
        self.actionSearch_Word.setText(_translate("MainWindow", "Search Word"))
        self.actionTranslate_Document.setText(_translate("MainWindow", "Translate Document"))
        self.actionDetect_Language.setText(_translate("MainWindow", "Detect Language"))
        self.actionPrograme_Language.setText(_translate("MainWindow", "Programe Language"))
        self.actionPrograme_Language_2.setText(_translate("MainWindow", "Programe Language"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.actionChinese.setText(_translate("MainWindow", "Chinese"))
        self.actionJapanese.setText(_translate("MainWindow", "Japanese"))
        self.actionOther_s.setText(_translate("MainWindow", "Other(s)"))
        self.actionEnglish_2.setText(_translate("MainWindow", "English"))
        self.actionChinese_2.setText(_translate("MainWindow", "Chinese"))
        self.actionJapanese_2.setText(_translate("MainWindow", "Japanese"))
        self.actionOther_s_2.setText(_translate("MainWindow", "Other(s)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

