# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QSplitter, QHBoxLayout, QTableWidget, QAbstractItemView
from TranslateMap import *

'''
This is a GUI for the word application
--------------------------------------
    Author: Runquan Ye
    Date: Sept/2020
--------------------------------------
'''

class Ui_MainWindow(object):
    langMap = TranslateMap().getLanguageMap()
    lIndex = 1
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 12, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.wordListTab = QtWidgets.QWidget()
        self.wordListTab.setObjectName("wordListTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wordListTab)
        self.gridLayout_2.setContentsMargins(8, 5, 8, 8)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.wordListTable = QtWidgets.QTableWidget(self.wordListTab)
        self.wordListTable.setRowCount(16)
        self.wordListTable.setColumnCount(4)
        self.wordListTable.setObjectName("wordListTable")
        self.wordListTable.setHorizontalHeaderLabels([self.langMap["WORD"][self.lIndex], self.langMap["PT"][self.lIndex], self.langMap["MEANING"][self.lIndex], self.langMap["PASTTERM"][self.lIndex]])
        self.wordListTable.setColumnWidth(2, MainWindow.width()/2)
        # self.wordListTable.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.Stretch)
        self.wordListTable.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.gridLayout_2.addWidget(self.wordListTable, 0, 0, 1, 1)

        self.tabWidget.addTab(self.wordListTab, "")
        self.headLlistSpanTab = QtWidgets.QWidget()
        self.headLlistSpanTab.setObjectName("headLlistSpanTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.headLlistSpanTab)
        self.gridLayout_3.setContentsMargins(8, 5, 8, 8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.container = QtWidgets.QFrame(self.headLlistSpanTab)
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.headSpanTable = QtWidgets.QTableWidget(self.container)
        self.headSpanTable.setGeometry(QtCore.QRect(170, 0, 541, 501))
        self.headSpanTable.setRowCount(16)
        self.headSpanTable.setColumnCount(4)
        self.headSpanTable.setHorizontalHeaderLabels([self.langMap["WORD"][self.lIndex], self.langMap["PT"][self.lIndex], self.langMap["MEANING"][self.lIndex],self.langMap["PASTTERM"][self.lIndex]])
        self.headSpanTable.setColumnWidth(2, MainWindow.width() / 2)
        # self.headSpanTable.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        self.headSpanTable.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.headSpanTable.setObjectName("headSpanTable")
        self.headSpanList = QtWidgets.QListWidget(self.container)
        self.headSpanList.setGeometry(QtCore.QRect(0, 0, 161, 501))
        self.headSpanList.setObjectName("headSpanList")

        #add the splitter
        hbox = QHBoxLayout()
        splitter = QSplitter(Qt.Horizontal)
        splitter.addWidget(self.headSpanList)
        splitter.addWidget(self.headSpanTable)
        splitter.setSizes([100, 200])
        hbox.addWidget(splitter)
        self.container.setLayout(hbox)

        self.gridLayout_3.addWidget(self.container, 0, 0, 1, 1)
        self.tabWidget.addTab(self.headLlistSpanTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuOperation = QtWidgets.QMenu(self.menubar)
        self.menuOperation.setObjectName("menuOperation")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_Programmer = QtWidgets.QAction(MainWindow)
        self.actionAbout_Programmer.setObjectName("actionAbout_Programmer")
        self.actionAbout_Application = QtWidgets.QAction(MainWindow)
        self.actionAbout_Application.setObjectName("actionAbout_Application")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionModify = QtWidgets.QAction(MainWindow)
        self.actionModify.setObjectName("actionModify")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionSelect_Dictionary = QtWidgets.QAction(MainWindow)
        self.actionSelect_Dictionary.setObjectName("actionSelect_Dictionary")
        self.actionSelect_Languary = QtWidgets.QAction(MainWindow)
        self.actionSelect_Languary.setObjectName("actionSelect_Languary")

        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionUpdate)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAdd)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionModify)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionReset)
        self.menuOperation.addAction(self.actionSelect_Dictionary)
        self.menuOperation.addAction(self.actionSelect_Languary)
        self.menuAbout.addAction(self.actionAbout_Application)
        self.menuAbout.addAction(self.actionAbout_Programmer)
        self.menuAbout.addSeparator()

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuOperation.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        # add button listener
        # self.actionOpen.triggered.connect(lambda pass)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", self.langMap["TITLE"][self.lIndex]))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wordListTab), _translate("MainWindow", self.langMap["WORDLIST"][self.lIndex]))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.headLlistSpanTab), _translate("MainWindow", self.langMap["HEADLIST"][self.lIndex]))
        self.menuFile.setTitle(_translate("MainWindow", self.langMap["FILE"][self.lIndex]))
        self.menuEdit.setTitle(_translate("MainWindow", self.langMap["EDIT"][self.lIndex]))
        self.menuOperation.setTitle(_translate("MainWindow", self.langMap["SETTING"][self.lIndex]))
        self.menuAbout.setTitle(_translate("MainWindow", self.langMap["ABOUT"][self.lIndex]))
        self.actionOpen.setText(_translate("MainWindow", self.langMap["OPEN"][self.lIndex]))
        self.actionOpen.setToolTip(_translate("MainWindow", self.langMap["OPEN_TIP"][self.lIndex]))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", self.langMap["SAVE"][self.lIndex]))
        self.actionSave.setToolTip(_translate("MainWindow", self.langMap["SAVE_TIP"][self.lIndex]))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionUpdate.setText(_translate("MainWindow", self.langMap["UPDATE"][self.lIndex]))
        self.actionUpdate.setToolTip(_translate("MainWindow", self.langMap["UPDATE_TIP"][self.lIndex]))
        self.actionUpdate.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionHelp.setText(_translate("MainWindow", self.langMap["HELP"][self.lIndex]))
        self.actionHelp.setToolTip(_translate("MainWindow", self.langMap["HELP_TIP"][self.lIndex]))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionExit.setText(_translate("MainWindow", self.langMap["EXIT"][self.lIndex]))
        self.actionExit.setToolTip(_translate("MainWindow", self.langMap["EXIT_TIP"][self.lIndex]))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Alt+F4"))

        self.actionAbout_Application.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.actionAdd.setText(_translate("MainWindow", self.langMap["ADD"][self.lIndex]))
        self.actionAdd.setToolTip(_translate("MainWindow", self.langMap["ADD_TIP"][self.lIndex]))
        self.actionAdd.setShortcut(_translate("MainWindow", "Ctrl+Alt+A"))
        self.actionDelete.setText(_translate("MainWindow", self.langMap["DELETE"][self.lIndex]))
        self.actionDelete.setToolTip(_translate("MainWindow", self.langMap["DELETE_TIP"][self.lIndex]))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Alt+D"))
        self.actionModify.setText(_translate("MainWindow", self.langMap["MODIFY"][self.lIndex]))
        self.actionModify.setToolTip(_translate("MainWindow", self.langMap["MODIFY_TIP"][self.lIndex]))
        self.actionModify.setShortcut(_translate("MainWindow", "Ctrl+Alt+M"))
        self.actionUndo.setText(_translate("MainWindow", self.langMap["UNDO"][self.lIndex]))
        self.actionUndo.setToolTip(_translate("MainWindow", self.langMap["UNDO_TIP"][self.lIndex]))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Alt+U"))
        self.actionReset.setText(_translate("MainWindow", self.langMap["REST"][self.lIndex]))
        self.actionReset.setToolTip(_translate("MainWindow", self.langMap["REST_TIP"][self.lIndex]))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+Alt+R"))
        self.actionSelect_Dictionary.setText(_translate("MainWindow", self.langMap["SELECT_DICT"][self.lIndex]))
        self.actionSelect_Dictionary.setToolTip(_translate("MainWindow", self.langMap["SELECT_DICT_TIP"][self.lIndex]))
        self.actionSelect_Dictionary.setShortcut(_translate("MainWindow", "Ctrl+Alt+E"))
        self.actionSelect_Languary.setText(_translate("MainWindow", self.langMap["SELECT_LANG"][self.lIndex]))
        self.actionSelect_Languary.setToolTip(_translate("MainWindow", self.langMap["SELECT_LANG_TIP"][self.lIndex]))
        self.actionSelect_Languary.setShortcut(_translate("MainWindow", "Ctrl+Alt+L"))
        self.actionAbout_Programmer.setText(_translate("MainWindow", self.langMap["ABOUT_PROGRAMMER"][self.lIndex]))
        self.actionAbout_Programmer.setToolTip(_translate("MainWindow", self.langMap["ABOUT_PROGRAMMER_TIP"][self.lIndex]))
        self.actionAbout_Programmer.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionAbout_Application.setText(_translate("MainWindow", self.langMap["ABOUT_PROJECT"][self.lIndex]))
        self.actionAbout_Application.setToolTip(_translate("MainWindow", self.langMap["ABOUT_PROJECT_TIP"][self.lIndex]))


    def getLangIndex(self):
        return self.lIndex


    def setLangIndex(self, index):
        if int(index) > 0:
            self.listNum = int(index)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
