# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QSplitter, QHBoxLayout

'''
This is a GUI for the word application
--------------------------------------
    Author: Runquan Ye
    Date: Sept/2020
--------------------------------------
'''

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 12, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.wordLlistTab = QtWidgets.QWidget()
        self.wordLlistTab.setObjectName("wordLlistTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wordLlistTab)
        self.gridLayout_2.setContentsMargins(8, 5, 8, 8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wordListTable = QtWidgets.QTableWidget(self.wordLlistTab)
        self.wordListTable.setRowCount(16)
        self.wordListTable.setColumnCount(7)
        self.wordListTable.setObjectName("wordListTable")
        self.gridLayout_2.addWidget(self.wordListTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.wordLlistTab, "")
        self.headLlistSpanTab = QtWidgets.QWidget()
        self.headLlistSpanTab.setObjectName("headLlistSpanTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.headLlistSpanTab)
        self.gridLayout_3.setContentsMargins(8, 5, 8, 8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.container = QtWidgets.QFrame(self.headLlistSpanTab)
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.headSpanTable = QtWidgets.QTableWidget(self.container)
        self.headSpanTable.setGeometry(QtCore.QRect(170, 0, 541, 501))
        self.headSpanTable.setRowCount(16)
        self.headSpanTable.setColumnCount(5)
        self.headSpanTable.setObjectName("headSpanTable")
        self.headSpanList = QtWidgets.QListWidget(self.container)
        self.headSpanList.setGeometry(QtCore.QRect(0, 0, 161, 501))
        self.headSpanList.setObjectName("headSpanList")

        #add the splitter
        hbox = QHBoxLayout()
        splitter = QSplitter(Qt.Horizontal)
        splitter.addWidget(self.headSpanList)
        splitter.addWidget(self.headSpanTable)
        splitter.setSizes([100, 200])
        hbox.addWidget(splitter)
        self.container.setLayout(hbox)

        self.gridLayout_3.addWidget(self.container, 0, 0, 1, 1)
        self.tabWidget.addTab(self.headLlistSpanTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuOperation = QtWidgets.QMenu(self.menubar)
        self.menuOperation.setObjectName("menuOperation")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_Programmer = QtWidgets.QAction(MainWindow)
        self.actionAbout_Programmer.setObjectName("actionAbout_Programmer")
        self.actionAbout_Application = QtWidgets.QAction(MainWindow)
        self.actionAbout_Application.setObjectName("actionAbout_Application")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionModify = QtWidgets.QAction(MainWindow)
        self.actionModify.setObjectName("actionModify")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionSelect_Dictionary = QtWidgets.QAction(MainWindow)
        self.actionSelect_Dictionary.setObjectName("actionSelect_Dictionary")
        self.actionSelect_Languary = QtWidgets.QAction(MainWindow)
        self.actionSelect_Languary.setObjectName("actionSelect_Languary")
        self.actionUML_Diagram = QtWidgets.QAction(MainWindow)
        self.actionUML_Diagram.setObjectName("actionUML_Diagram")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionUpdate)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAdd)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionModify)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionReset)
        self.menuOperation.addAction(self.actionSelect_Dictionary)
        self.menuOperation.addAction(self.actionSelect_Languary)
        self.menuAbout.addAction(self.actionAbout_Application)
        self.menuAbout.addAction(self.actionAbout_Programmer)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionUML_Diagram)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuOperation.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        # add button listener
        # self.actionOpen.triggered.connect(lambda pass)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wordLlistTab), _translate("MainWindow", "Word List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.headLlistSpanTab), _translate("MainWindow", "Head List"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuOperation.setTitle(_translate("MainWindow", "Setting"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open File"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save File"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))
        self.actionUpdate.setToolTip(_translate("MainWindow", "Update Application Data"))
        self.actionUpdate.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setToolTip(_translate("MainWindow", "Application Instruction"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Quit Application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Alt+F4"))
        self.actionAbout_Programmer.setText(_translate("MainWindow", "About Programmer"))
        self.actionAbout_Programmer.setToolTip(_translate("MainWindow", "Show My Profile"))
        self.actionAbout_Programmer.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionAbout_Application.setText(_translate("MainWindow", "About Project"))
        self.actionAbout_Application.setToolTip(_translate("MainWindow", "Show Project Description"))
        self.actionAbout_Application.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionAdd.setToolTip(_translate("MainWindow", "Add New Word"))
        self.actionAdd.setShortcut(_translate("MainWindow", "Ctrl+Alt+A"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDelete.setToolTip(_translate("MainWindow", "Delete Word"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Alt+D"))
        self.actionModify.setText(_translate("MainWindow", "Modify"))
        self.actionModify.setToolTip(_translate("MainWindow", "Modify Word"))
        self.actionModify.setShortcut(_translate("MainWindow", "Ctrl+Alt+M"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setToolTip(_translate("MainWindow", "Undo Last Edit Order"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Alt+U"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setToolTip(_translate("MainWindow", "Reset Application Data"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+Alt+R"))
        self.actionSelect_Dictionary.setText(_translate("MainWindow", "Select Dictionary"))
        self.actionSelect_Dictionary.setToolTip(_translate("MainWindow", "Select Source Dictionary"))
        self.actionSelect_Dictionary.setShortcut(_translate("MainWindow", "Ctrl+Alt+E"))
        self.actionSelect_Languary.setText(_translate("MainWindow", "Select Languary"))
        self.actionSelect_Languary.setToolTip(_translate("MainWindow", "Select  Application Languary"))
        self.actionSelect_Languary.setShortcut(_translate("MainWindow", "Ctrl+Alt+L"))
        self.actionUML_Diagram.setText(_translate("MainWindow", "UML Diagram"))
        self.actionUML_Diagram.setToolTip(_translate("MainWindow", "Show Project UML Diagram"))
        self.actionUML_Diagram.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
